### ISSUE TITLE
Build of docs on RTD failing

### ISSUE THREAD

**Issue by arporter** [stfc/fparser#393]
The failure is:

    Traceback (most recent call last):
      File "/home/docs/checkouts/readthedocs.org/user_builds/fparser/envs/latest/lib/python3.7/site- 
       packages/sphinx/registry.py", line 459, in load_extension
        mod = import_module(extname)
      File "/home/docs/checkouts/readthedocs.org/user_builds/fparser/envs/latest/lib/python3.7/importlib/__init__.py", line 127, 
    in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'autoapi.extension'

**Comment by arporter** [comment]
I was naughty and fixed this as part of #391 (just needed a new line adding to the pip_requirements.txt file for the docs build).
