### ISSUE TITLE
Issue with Parsing Comments in Fixed-form Fortran w/ Include

### ISSUE THREAD

**Issue by mjklemm** [stfc/fparser#407]
The parser throws an error for this code snippet:

```Fortran
      subroutine foobar (a,b,c)
c     Some comment
#include "some.inc"
      end subroutine foobar
```

Error reported by the parser:

```
Traceback (most recent call last):
  File "C:\Users\micha\PycharmProjects\fortran_offload\fparser\two\Fortran2003.py", line 266, in __new__
    return Base.__new__(cls, string)
  File "C:\Users\micha\PycharmProjects\fortran_offload\fparser\two\utils.py", line 487, in __new__
    raise NoMatchError(errmsg)
fparser.two.utils.NoMatchError: at line 2
>>>c     Some comment


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micha\PycharmProjects\fortran_offload\main.py", line 51, in <module>
    parse_tree = f08_parser(reader)
  File "C:\Users\micha\PycharmProjects\fortran_offload\fparser\two\Fortran2003.py", line 270, in __new__
    raise FortranSyntaxError(string, "")
fparser.two.utils.FortranSyntaxError: at line 2
>>>c     Some comment
```

The error goes away when the `#include` is removed.

**Comment by arporter** [comment]
I think the problem here is the `#include` - fparser has only very limited support for pre-processor macros (since they aren't Fortran, see e.g. #333). You could try using the Fortran `include` instead?

**Comment by mjklemm** [comment]
Ok, that seems to work better.  I think I can manage to run the preprocessor first and provide "clean" Fortran to fparser.

**Comment by mjklemm** [comment]
PS: Closing this as "user error" :-)
